### ISSUE TITLE
Don't use interdependencies between services

### ISSUE THREAD

**Issue by parkito** [volpert13/javaschool#14]
https://github.com/volpert13/javaschool/blob/926b5d70da5a7ec2758c6d9bbc35ed46f17522db/MetroInformator/src/main/java/ru/javasch/metro/service/implementations/UserServiceImpl.java#L29

In service layer try to use repositories. Services in services isn't good architectural approach

**Comment by volpert13** [comment]
Interdependencies deleted where it's possible.
