### ISSUE TITLE
Use H2 db for unit tests

### ISSUE THREAD

**Issue by parkito** [volpert13/javaschool#15]
https://github.com/volpert13/javaschool/blob/926b5d70da5a7ec2758c6d9bbc35ed46f17522db/MetroInformator/src/test/java/ru/javasch/metro/integrations/GraphServiceJTest.java#L41

Using real data base isn't good idea. For unit and integration test much suitable using test db such H2

**Comment by volpert13** [comment]
Now use minidatabase in docker container for tests
